//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAAS_SCFAMA.WS_SCFAMA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_SCFAMA.WSPAASSCFAMASoap")]
    public interface WSPAASSCFAMASoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _Campos del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserAuthentication", ReplyAction="*")]
        PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationResponse UserAuthentication(PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationResponse> UserAuthenticationAsync(PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserAuthentication", Namespace="http://tempuri.org/", Order=0)]
        public PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequestBody Body;
        
        public UserAuthenticationRequest() {
        }
        
        public UserAuthenticationRequest(PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PAAS_SCFAMA.WS_SCFAMA.ArrayOfString _Campos;
        
        public UserAuthenticationRequestBody() {
        }
        
        public UserAuthenticationRequestBody(PAAS_SCFAMA.WS_SCFAMA.ArrayOfString _Campos) {
            this._Campos = _Campos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserAuthenticationResponse", Namespace="http://tempuri.org/", Order=0)]
        public PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationResponseBody Body;
        
        public UserAuthenticationResponse() {
        }
        
        public UserAuthenticationResponse(PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PAAS_SCFAMA.WS_SCFAMA.ArrayOfString UserAuthenticationResult;
        
        public UserAuthenticationResponseBody() {
        }
        
        public UserAuthenticationResponseBody(PAAS_SCFAMA.WS_SCFAMA.ArrayOfString UserAuthenticationResult) {
            this.UserAuthenticationResult = UserAuthenticationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSPAASSCFAMASoapChannel : PAAS_SCFAMA.WS_SCFAMA.WSPAASSCFAMASoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPAASSCFAMASoapClient : System.ServiceModel.ClientBase<PAAS_SCFAMA.WS_SCFAMA.WSPAASSCFAMASoap>, PAAS_SCFAMA.WS_SCFAMA.WSPAASSCFAMASoap {
        
        public WSPAASSCFAMASoapClient() {
        }
        
        public WSPAASSCFAMASoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPAASSCFAMASoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPAASSCFAMASoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPAASSCFAMASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationResponse PAAS_SCFAMA.WS_SCFAMA.WSPAASSCFAMASoap.UserAuthentication(PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequest request) {
            return base.Channel.UserAuthentication(request);
        }
        
        public PAAS_SCFAMA.WS_SCFAMA.ArrayOfString UserAuthentication(PAAS_SCFAMA.WS_SCFAMA.ArrayOfString _Campos) {
            PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequest inValue = new PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequest();
            inValue.Body = new PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequestBody();
            inValue.Body._Campos = _Campos;
            PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationResponse retVal = ((PAAS_SCFAMA.WS_SCFAMA.WSPAASSCFAMASoap)(this)).UserAuthentication(inValue);
            return retVal.Body.UserAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationResponse> PAAS_SCFAMA.WS_SCFAMA.WSPAASSCFAMASoap.UserAuthenticationAsync(PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequest request) {
            return base.Channel.UserAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationResponse> UserAuthenticationAsync(PAAS_SCFAMA.WS_SCFAMA.ArrayOfString _Campos) {
            PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequest inValue = new PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequest();
            inValue.Body = new PAAS_SCFAMA.WS_SCFAMA.UserAuthenticationRequestBody();
            inValue.Body._Campos = _Campos;
            return ((PAAS_SCFAMA.WS_SCFAMA.WSPAASSCFAMASoap)(this)).UserAuthenticationAsync(inValue);
        }
    }
}
